import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFAAAA",
    //paddingStart: 12,
  },
  profileTop: {
    //borderBottomWidth: 2,
  },
  containerHeader: {
    borderBottomColor: "black",
    height: 80,
    width: "100%",
  },
  text: {
    //fontFamily: "HelveticaNeue",
    color: "#52575D",
  },
  image: {
    flex: 1,
    height: undefined,
    width: undefined,
    borderRadius: 10,
  },
  subText: {
    fontSize: 12,
    color: "#AEB5BC",
    textTransform: "uppercase",
    fontWeight: "500",
  },
  profileImageContainer: {
    //alignSelf: "center",
    flexDirection: "row",
    flex: 1,
    paddingLeft: 12,
  },
  profileImage: {
    // Change this
    //height: 5,
    marginTop: 60,
    borderWidth: 3,
    borderRadius: 80,
    width: "23.5%",
    // alignItems: "center",
    // justifyContent: "center",
  },
  buttonsContainer: {
    marginTop: 70,
    flex: 1,
    paddingRight: 20,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    alignItems: "center",
    flexDirection: "row",
  },
  dm: {
    backgroundColor: "#41444B",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginEnd: 5,
  },
  follow: {
    backgroundColor: "#41444B",
    width: 80,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  infoContainer: {
    // alignSelf: "center",
    // alignItems: "center",
    marginTop: 16,
    flexDirection: "column",
    paddingLeft: 12,
  },
  statsContainer: {
    flexDirection: "column",
    alignSelf: "center",
    marginTop: 32,
    paddingLeft: 12,
  },
  statsBox: {
    alignItems: "center",
    flex: 1,
  },
  row: {
    flexDirection: "row",
    marginBottom: 10,
    marginRight: 20,
  },
  userInfoSection: {
    paddingHorizontal: 0,
    marginBottom: 3,
    flexDirection: "row",
    // justifyContent: "center",
    // alignItems: "center",
    marginTop: 15,
    paddingStart: 12,
  },
  userInfoSectionLower: {
    paddingHorizontal: 2,
    marginBottom: 0,
    flexDirection: "row",
    // justifyContent: "center",
    // alignItems: "center",
    marginTop: 0,
    paddingStart: 12,
  },
  infoBoxWrapper: {
    borderTopColor: "#dddddd",
    //borderTopWidth: 0.5,
    flexDirection: "row",
    width: "100%",
    //height: 100,
    //justifyContent: "center",
    paddingStart: 12,
  },
  infoBox: {
    marginRight: 30,
    // alignItems: "center",
    // justifyContent: "center",
  },

  menuItem: {
    flexDirection: "row",
    paddingVertical: 15,
    paddingHorizontal: 30,
  },
  menuItemText: {
    color: "#777777",
    fontWeight: "600",
    fontSize: 16,
    lineHeight: 26,
  },
  myposts: {
    //marginHorizontal: 10,
    marginTop: 60,
  },
  MyPostFeedItem: {
    flex: 1,
    backgroundColor: "#FFF",
    padding: 0,
    flexDirection: "column",
    marginVertical: 0,
    //marginTop: 10,
    //marginHorizontal: 10,
    width: "100%",
    borderColor: "gray",
    marginVertical: 2,
    //borderBottomWidth: 2,
    minHeight: 100,
  },
  feedHeader: {
    paddingTop: 9,
    flex: 0.5,
    flexDirection: "row",
    //alignItems: "center",
    paddingLeft: 12,
    height: 25,
  },
  userAvatar: {
    paddingTop: 9,
    flex: 0.3,
    flexDirection: "row",
    //alignItems: "center",
    paddingLeft: 12,
    //height: 50,
  },
  userText: {
    //flex: 0.1,
    //paddingRight: 12,
    //paddingRight: 50,
    flexDirection: "row",
    //paddingBottom: 10,
  },
  moreButton: {
    height: 80,
    flex: 0.1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingBottom: 40,
  },

  mainText: {
    paddingLeft: 16,
  },
  loneText: {
    paddingLeft: 0,
  },

  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 16,
  },
  name: {
    fontSize: 14,
    fontWeight: "500",
    color: "#454D65",
    //marginLeft: 12,
    paddingBottom: 15,
    flexDirection: "row",
    //paddingRight: 5,
  },
  timestamp: {
    fontSize: 11,
    color: "#C4C6CE",
    marginTop: 2,
    //paddingBottom: 50,
    flexDirection: "row",
  },
  post: {
    fontSize: 14,
    marginLeft: 55,
  },
  postImage: {
    width: "100%",
    height: 200,
    borderRadius: 5,
    marginVertical: 16,
    alignSelf: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
});

export default styles;
